export interface BaseQuizQuestion {
  id: number;
  week: number;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

// 10 Weekly Base Chain Quizzes (10 questions each = 100 questions total)
export const BASE_QUIZ_DATA: BaseQuizQuestion[] = [
  // ═══ WEEK 1: Base Fundamentals ═══
  { id: 1, week: 1, difficulty: 'easy', question: "What is Base?", options: ["A Layer 1 blockchain", "An Ethereum Layer 2 rollup incubated by Coinbase", "A Bitcoin sidechain", "A cryptocurrency exchange"], answer: "An Ethereum Layer 2 rollup incubated by Coinbase", explanation: "Base is a secure, low-cost, builder-friendly Ethereum Layer 2 (L2) solution built on the OP Stack and incubated by Coinbase. It provides a safe on-ramp for anyone wanting to build or use decentralized apps." },
  { id: 2, week: 1, difficulty: 'easy', question: "Which technology stack does Base use?", options: ["zk-SNARK stack", "The OP Stack (Optimism)", "Polygon SDK", "Cosmos SDK"], answer: "The OP Stack (Optimism)", explanation: "Base is built on the OP Stack, which is the open-source development framework created by the Optimism Collective. This means Base benefits from the Superchain vision." },
  { id: 3, week: 1, difficulty: 'easy', question: "Who incubated Base?", options: ["Binance", "Coinbase", "Ethereum Foundation", "OpenSea"], answer: "Coinbase", explanation: "Base was incubated by Coinbase, one of the world's largest and most trusted cryptocurrency exchanges. However, Base is designed to be decentralized beyond Coinbase." },
  { id: 4, week: 1, difficulty: 'medium', question: "What is Base's chain ID?", options: ["1", "137", "8453", "42161"], answer: "8453", explanation: "Base's chain ID is 8453 (hex: 0x2105). This uniquely identifies the Base network for wallet connections and RPC calls." },
  { id: 5, week: 1, difficulty: 'medium', question: "What consensus mechanism does Base use?", options: ["Proof of Work", "Proof of Stake", "Optimistic Rollup (inherits Ethereum's security)", "Delegated Proof of Stake"], answer: "Optimistic Rollup (inherits Ethereum's security)", explanation: "Base uses Optimistic Rollups, posting transaction data to Ethereum L1 and inheriting Ethereum's security. Transactions are assumed valid unless challenged during the dispute period." },
  { id: 6, week: 1, difficulty: 'easy', question: "What is the native gas token on Base?", options: ["BASE token", "USDC", "ETH (Ether)", "OP token"], answer: "ETH (Ether)", explanation: "Base uses ETH as its native gas token, the same as Ethereum mainnet. You need bridged ETH on Base to pay for transaction fees." },
  { id: 7, week: 1, difficulty: 'medium', question: "What is the Superchain?", options: ["A mining pool", "A network of interoperable L2 chains built on the OP Stack", "Coinbase's blockchain", "A Layer 3 solution"], answer: "A network of interoperable L2 chains built on the OP Stack", explanation: "The Superchain is a vision for a network of L2 chains that share security, a communication layer, and an open-source technology stack (OP Stack). Base is a core member." },
  { id: 8, week: 1, difficulty: 'hard', question: "Does Base have its own native token?", options: ["Yes, the BASE token", "Yes, but it's not yet launched", "No, Base has no plans for a native token", "Yes, you can mine it"], answer: "No, Base has no plans for a native token", explanation: "Base has explicitly stated it has no plans to issue a native network token. It uses ETH for gas and is focused on building an open economy rather than launching a token." },
  { id: 9, week: 1, difficulty: 'easy', question: "What year was Base launched?", options: ["2021", "2022", "2023", "2024"], answer: "2023", explanation: "Base launched its mainnet to the public in August 2023 after a successful testnet period. It quickly grew into one of the most active L2 networks." },
  { id: 10, week: 1, difficulty: 'medium', question: "What is the main benefit of building on Base vs Ethereum L1?", options: ["More validators", "Lower transaction fees and faster finality", "Different programming language", "No smart contracts needed"], answer: "Lower transaction fees and faster finality", explanation: "Base offers significantly lower gas fees (often under $0.01) and faster transaction confirmation compared to Ethereum L1, while inheriting Ethereum's security." },

  // ═══ WEEK 2: Base Ecosystem & DApps ═══
  { id: 11, week: 2, difficulty: 'easy', question: "What is Basenames?", options: ["A game on Base", "A naming service for Base addresses (like ENS)", "A DEX on Base", "A bridge protocol"], answer: "A naming service for Base addresses (like ENS)", explanation: "Basenames is an on-chain identity system that lets you register human-readable names (like 'alice.base') for your wallet address on the Base network." },
  { id: 12, week: 2, difficulty: 'easy', question: "What is Aerodrome?", options: ["An NFT marketplace", "A weather app", "The leading DEX and liquidity hub on Base", "A bridge from Ethereum"], answer: "The leading DEX and liquidity hub on Base", explanation: "Aerodrome is the central liquidity hub and decentralized exchange (DEX) on Base, built as a next-gen AMM with vote-escrow tokenomics to attract deep liquidity." },
  { id: 13, week: 2, difficulty: 'medium', question: "Which bridge is the official Base bridge?", options: ["Wormhole Bridge", "Base Bridge (bridge.base.org)", "Polygon Bridge", "Hop Protocol"], answer: "Base Bridge (bridge.base.org)", explanation: "The official Base Bridge at bridge.base.org allows users to move ETH and supported tokens between Ethereum L1 and Base L2 securely." },
  { id: 14, week: 2, difficulty: 'easy', question: "What is friend.tech?", options: ["A coding tool", "A social platform for tokenized connections on Base", "A wallet app", "Base's official dApp"], answer: "A social platform for tokenized connections on Base", explanation: "friend.tech is a social application built on Base that lets users buy and sell 'keys' (formerly shares) of other users, creating a tokenized social network." },
  { id: 15, week: 2, difficulty: 'medium', question: "What smart contract language do Base developers use?", options: ["Python", "JavaScript", "Solidity (and Vyper)", "Rust"], answer: "Solidity (and Vyper)", explanation: "Since Base is EVM-compatible, developers use Solidity (the primary language) and Vyper to write smart contracts, just like they do on Ethereum." },
  { id: 16, week: 2, difficulty: 'easy', question: "What is Farcaster?", options: ["A blockchain", "A decentralized social protocol popular on Base", "A DeFi protocol", "A game engine"], answer: "A decentralized social protocol popular on Base", explanation: "Farcaster is a sufficiently decentralized social media protocol with a strong community on Base. Warpcast is its most popular client application." },
  { id: 17, week: 2, difficulty: 'medium', question: "What is USDC on Base?", options: ["A wrapped version of USDC", "Natively issued USDC by Circle on Base", "A bridged stablecoin", "A synthetic dollar"], answer: "Natively issued USDC by Circle on Base", explanation: "Circle issues USDC natively on Base, meaning it's a first-class stablecoin on the network, not a bridged/wrapped version. This provides better security and direct redemption." },
  { id: 18, week: 2, difficulty: 'hard', question: "What percentage of sequencer revenue does Base contribute to the Optimism Collective?", options: ["5%", "10%", "15%", "25%"], answer: "15%", explanation: "Base contributes 15% of its sequencer revenue (or 2.5% of total revenue, whichever is greater) to the Optimism Collective, as part of its commitment to the Superchain." },
  { id: 19, week: 2, difficulty: 'easy', question: "What is Coinbase Wallet?", options: ["A hardware wallet only", "A self-custody crypto wallet that works great with Base", "A centralized bank", "A mining tool"], answer: "A self-custody crypto wallet that works great with Base", explanation: "Coinbase Wallet is a self-custody wallet (you hold your own keys) that provides seamless integration with Base for transactions, dApps, and NFTs." },
  { id: 20, week: 2, difficulty: 'medium', question: "What is Base Camp?", options: ["A physical location", "A developer onboarding and learning resource for Base", "A gaming platform", "A staking protocol"], answer: "A developer onboarding and learning resource for Base", explanation: "Base Camp is Coinbase's developer education platform that teaches smart contract development on Base with hands-on exercises and tutorials." },

  // ═══ WEEK 3: Smart Contracts on Base ═══
  { id: 21, week: 3, difficulty: 'easy', question: "What is a smart contract?", options: ["A legal document", "Self-executing code deployed on the blockchain", "An AI program", "A paper agreement"], answer: "Self-executing code deployed on the blockchain", explanation: "Smart contracts are programs stored on the blockchain that automatically execute when predetermined conditions are met. They're the building blocks of dApps." },
  { id: 22, week: 3, difficulty: 'medium', question: "What EVM version does Base support?", options: ["Berlin", "London", "Shanghai", "Dencun"], answer: "Dencun", explanation: "Base supports the latest Ethereum Virtual Machine (EVM) versions including the Dencun upgrade, which introduced EIP-4844 blob transactions for cheaper data availability." },
  { id: 23, week: 3, difficulty: 'medium', question: "What is EIP-4844?", options: ["A token standard", "Proto-danksharding that reduces L2 costs with blob transactions", "A consensus change", "A wallet standard"], answer: "Proto-danksharding that reduces L2 costs with blob transactions", explanation: "EIP-4844 (Proto-Danksharding) introduced 'blob' transactions which dramatically reduced the cost of posting L2 data to Ethereum L1, making Base fees even cheaper." },
  { id: 24, week: 3, difficulty: 'easy', question: "What tool is commonly used to deploy contracts on Base?", options: ["Visual Studio", "Hardhat or Foundry", "Photoshop", "Excel"], answer: "Hardhat or Foundry", explanation: "Hardhat and Foundry are the two most popular development frameworks for compiling, testing, and deploying smart contracts on Base (and any EVM chain)." },
  { id: 25, week: 3, difficulty: 'medium', question: "What is the Base Goerli/Sepolia testnet used for?", options: ["Mining tokens", "Testing dApps before deploying to mainnet", "Storing real assets", "Faster mainnet transactions"], answer: "Testing dApps before deploying to mainnet", explanation: "Base Sepolia is a testnet where developers can test their smart contracts and dApps with fake ETH before deploying to the real Base mainnet." },
  { id: 26, week: 3, difficulty: 'hard', question: "What is the CREATE2 opcode used for?", options: ["Creating tokens", "Deploying contracts to deterministic addresses", "Creating wallets", "Mining rewards"], answer: "Deploying contracts to deterministic addresses", explanation: "CREATE2 allows deploying a contract to a pre-computable address. This is useful for counterfactual instantiation (e.g., multi-sig wallets) and cross-chain deployments." },
  { id: 27, week: 3, difficulty: 'easy', question: "What is the ERC-20 standard?", options: ["An NFT standard", "A standard interface for fungible tokens", "A bridge protocol", "A consensus algorithm"], answer: "A standard interface for fungible tokens", explanation: "ERC-20 is the standard interface for fungible tokens on EVM chains like Base. It defines functions like transfer(), approve(), and balanceOf()." },
  { id: 28, week: 3, difficulty: 'medium', question: "What is OpenZeppelin?", options: ["A blockchain", "A library of audited, reusable smart contract code", "A cryptocurrency", "A mining pool"], answer: "A library of audited, reusable smart contract code", explanation: "OpenZeppelin provides a battle-tested library of smart contract components (ERC-20, ERC-721, access control, etc.) that developers use to build secure contracts on Base." },
  { id: 29, week: 3, difficulty: 'hard', question: "What is a proxy contract pattern?", options: ["A contract that blocks transactions", "A pattern allowing upgradeable smart contracts", "A mining contract", "A DEX contract"], answer: "A pattern allowing upgradeable smart contracts", explanation: "Proxy patterns separate the contract's logic from its storage, enabling developers to upgrade the logic while keeping the same address and stored data." },
  { id: 30, week: 3, difficulty: 'medium', question: "What is Etherscan for Base called?", options: ["Basescan", "BaseExplorer", "CoinbaseScan", "OptiScan"], answer: "Basescan", explanation: "Basescan (basescan.org) is the block explorer for Base, built by the Etherscan team. It lets you view transactions, contracts, tokens, and analytics on Base." },

  // ═══ WEEK 4: DeFi on Base ═══
  { id: 31, week: 4, difficulty: 'easy', question: "What does DeFi stand for?", options: ["Decentralized Files", "Decentralized Finance", "Digital Finance", "Direct Finance"], answer: "Decentralized Finance", explanation: "DeFi stands for Decentralized Finance — financial services (lending, borrowing, trading, etc.) built on blockchain technology without traditional intermediaries." },
  { id: 32, week: 4, difficulty: 'medium', question: "What is an AMM?", options: ["Automatic Money Machine", "Automated Market Maker", "Advanced Mining Module", "Automated Message Manager"], answer: "Automated Market Maker", explanation: "An AMM is a type of DEX that uses mathematical formulas (like x*y=k) to price assets in liquidity pools, enabling permissionless trading without order books." },
  { id: 33, week: 4, difficulty: 'medium', question: "What is Total Value Locked (TVL)?", options: ["Total coins mined", "Total money deposited in DeFi protocols", "Total transactions volume", "Total wallets created"], answer: "Total money deposited in DeFi protocols", explanation: "TVL measures the total value of crypto assets deposited/locked in DeFi protocols. Base has billions of dollars in TVL across various DeFi applications." },
  { id: 34, week: 4, difficulty: 'easy', question: "What is yield farming?", options: ["A crypto game", "Earning rewards by providing liquidity to DeFi protocols", "Mining cryptocurrency", "Buying NFTs"], answer: "Earning rewards by providing liquidity to DeFi protocols", explanation: "Yield farming involves depositing your crypto into DeFi protocols (like liquidity pools) to earn rewards, usually in the form of fees or token incentives." },
  { id: 35, week: 4, difficulty: 'hard', question: "What is impermanent loss?", options: ["Permanent crypto loss", "Temporary loss from providing liquidity when prices change", "A network fee", "A smart contract bug"], answer: "Temporary loss from providing liquidity when prices change", explanation: "Impermanent loss occurs when the price ratio of tokens in a liquidity pool changes from when you deposited, resulting in less value than if you had just held the tokens." },
  { id: 36, week: 4, difficulty: 'medium', question: "What is a liquidity pool?", options: ["A swimming pool", "A collection of tokens locked in a smart contract for trading", "A mining pool", "A wallet"], answer: "A collection of tokens locked in a smart contract for trading", explanation: "Liquidity pools are smart contracts containing pairs of tokens that enable decentralized trading. Providers earn fees from trades proportional to their share." },
  { id: 37, week: 4, difficulty: 'easy', question: "What is a stablecoin?", options: ["A volatile token", "A cryptocurrency designed to maintain a stable value (e.g., $1)", "A mining reward", "A governance token"], answer: "A cryptocurrency designed to maintain a stable value (e.g., $1)", explanation: "Stablecoins like USDC are designed to maintain a stable value, usually pegged 1:1 to the US dollar. They're widely used on Base for trading and payments." },
  { id: 38, week: 4, difficulty: 'medium', question: "What is a flash loan?", options: ["A quick bank loan", "An uncollateralized loan that must be repaid within one transaction", "A government grant", "A crypto gift"], answer: "An uncollateralized loan that must be repaid within one transaction", explanation: "Flash loans allow borrowing any amount without collateral, as long as the loan is repaid within the same blockchain transaction. They enable arbitrage and liquidations." },
  { id: 39, week: 4, difficulty: 'hard', question: "What is MEV (Maximal Extractable Value)?", options: ["Maximum ETH Value", "Value that can be extracted by ordering/censoring transactions", "Minimum Exchange Value", "Market Exchange Volume"], answer: "Value that can be extracted by ordering/censoring transactions", explanation: "MEV refers to the profit that block producers can make by reordering, including, or censoring transactions within a block. It's a key challenge in DeFi." },
  { id: 40, week: 4, difficulty: 'easy', question: "What is a DEX?", options: ["A digital exchange license", "A Decentralized Exchange for peer-to-peer trading", "A development tool", "A database"], answer: "A Decentralized Exchange for peer-to-peer trading", explanation: "A DEX (Decentralized Exchange) allows users to trade crypto directly from their wallets without intermediaries. Aerodrome, Uniswap, and others operate on Base." },

  // ═══ WEEK 5: NFTs & Digital Assets on Base ═══
  { id: 41, week: 5, difficulty: 'easy', question: "What does NFT stand for?", options: ["New File Type", "Non-Fungible Token", "Network Function Tool", "National Finance Token"], answer: "Non-Fungible Token", explanation: "NFT stands for Non-Fungible Token — a unique digital asset on the blockchain that represents ownership of art, music, collectibles, and more." },
  { id: 42, week: 5, difficulty: 'medium', question: "What is the ERC-721 standard?", options: ["A fungible token standard", "The standard for non-fungible tokens (NFTs)", "A bridge standard", "A staking standard"], answer: "The standard for non-fungible tokens (NFTs)", explanation: "ERC-721 is the standard interface for NFTs on EVM chains. Each token is unique and has a distinct tokenId, making it perfect for digital collectibles." },
  { id: 43, week: 5, difficulty: 'medium', question: "What is ERC-1155?", options: ["A stablecoin standard", "A multi-token standard supporting both fungible and non-fungible tokens", "A governance standard", "A bridge standard"], answer: "A multi-token standard supporting both fungible and non-fungible tokens", explanation: "ERC-1155 is a versatile standard that can handle both fungible and non-fungible tokens in a single contract, making it more gas-efficient for batch operations." },
  { id: 44, week: 5, difficulty: 'easy', question: "What is minting an NFT?", options: ["Buying crypto", "Creating and publishing a new NFT on the blockchain", "Deleting an NFT", "Transferring tokens"], answer: "Creating and publishing a new NFT on the blockchain", explanation: "Minting is the process of creating a new NFT by writing it to the blockchain. On Base, minting is very affordable due to low gas fees." },
  { id: 45, week: 5, difficulty: 'medium', question: "What is an NFT marketplace?", options: ["A physical store", "A platform where users can buy, sell, and trade NFTs", "A mining pool", "A blockchain"], answer: "A platform where users can buy, sell, and trade NFTs", explanation: "NFT marketplaces like OpenSea, Zora, and others on Base provide platforms for creators and collectors to trade digital assets." },
  { id: 46, week: 5, difficulty: 'hard', question: "What are on-chain NFTs?", options: ["NFTs stored on the internet", "NFTs where the artwork/data is stored entirely on the blockchain", "NFTs with no metadata", "Stolen NFTs"], answer: "NFTs where the artwork/data is stored entirely on the blockchain", explanation: "On-chain NFTs store all their data (including artwork) directly on the blockchain rather than pointing to external IPFS/HTTP links. This ensures permanence." },
  { id: 47, week: 5, difficulty: 'easy', question: "Why are NFTs cheaper to mint on Base than Ethereum?", options: ["Base uses different code", "Base has lower gas fees as an L2 rollup", "NFTs are smaller on Base", "Base doesn't charge for minting"], answer: "Base has lower gas fees as an L2 rollup", explanation: "As a Layer 2 rollup, Base bundles many transactions together and posts them to Ethereum L1, dramatically reducing the per-transaction gas cost." },
  { id: 48, week: 5, difficulty: 'medium', question: "What is Zora on Base?", options: ["A DeFi protocol", "An NFT creation and marketplace platform on Base", "A stablecoin", "A wallet"], answer: "An NFT creation and marketplace platform on Base", explanation: "Zora is a prominent NFT platform operating on Base that allows creators to mint and sell digital art, music, and collectibles with minimal fees." },
  { id: 49, week: 5, difficulty: 'medium', question: "What is token-gating?", options: ["Burning tokens", "Restricting access to content/features based on token ownership", "Creating new tokens", "Trading tokens"], answer: "Restricting access to content/features based on token ownership", explanation: "Token-gating uses NFT or token ownership to control access to exclusive content, communities, or features. It's a powerful utility for NFTs on Base." },
  { id: 50, week: 5, difficulty: 'hard', question: "What is ERC-6551 (Token Bound Accounts)?", options: ["A standard for stablecoins", "A standard that gives NFTs their own smart contract wallet", "A bridge standard", "A new consensus mechanism"], answer: "A standard that gives NFTs their own smart contract wallet", explanation: "ERC-6551 allows NFTs to own other assets by giving each NFT its own smart contract account. This enables NFTs to hold tokens, other NFTs, and interact with dApps." },

  // ═══ WEEK 6: Wallets & Security on Base ═══
  { id: 51, week: 6, difficulty: 'easy', question: "What is a crypto wallet?", options: ["A physical wallet", "Software/hardware that stores private keys for blockchain interaction", "A bank account", "An exchange"], answer: "Software/hardware that stores private keys for blockchain interaction", explanation: "A crypto wallet stores your private keys and allows you to send, receive, and manage your digital assets on the blockchain. It's your gateway to Web3." },
  { id: 52, week: 6, difficulty: 'easy', question: "What is a private key?", options: ["Your username", "A secret cryptographic key that controls your wallet", "Your password to an exchange", "A public address"], answer: "A secret cryptographic key that controls your wallet", explanation: "A private key is a secret number that proves ownership of your crypto. NEVER share it! Anyone with your private key can access and move all your funds." },
  { id: 53, week: 6, difficulty: 'medium', question: "What is a seed phrase (mnemonic)?", options: ["A random sentence", "12-24 words that can recover your wallet's private key", "A password hint", "An API key"], answer: "12-24 words that can recover your wallet's private key", explanation: "A seed phrase (also called mnemonic or recovery phrase) is a human-readable representation of your private key. Store it offline and NEVER share it." },
  { id: 54, week: 6, difficulty: 'easy', question: "What is the difference between hot and cold wallets?", options: ["Temperature", "Hot wallets are connected to internet, cold are offline", "Hot wallets are newer", "Cold wallets are larger"], answer: "Hot wallets are connected to internet, cold are offline", explanation: "Hot wallets (MetaMask, Coinbase Wallet) are always connected to the internet for easy access. Cold wallets (Ledger, Trezor) store keys offline for maximum security." },
  { id: 55, week: 6, difficulty: 'medium', question: "What is a smart contract wallet?", options: ["A regular wallet", "A wallet controlled by a smart contract with programmable rules", "A government wallet", "A mining wallet"], answer: "A wallet controlled by a smart contract with programmable rules", explanation: "Smart contract wallets (like Safe multisig) are controlled by smart contract code, enabling features like multi-signature, spending limits, and social recovery." },
  { id: 56, week: 6, difficulty: 'hard', question: "What is account abstraction (ERC-4337)?", options: ["Deleting accounts", "Making smart contract wallets act like regular accounts with better UX", "A new blockchain", "An L3 solution"], answer: "Making smart contract wallets act like regular accounts with better UX", explanation: "Account Abstraction (ERC-4337) enables smart contract wallets with features like gasless transactions, batch operations, and social recovery — all without protocol changes." },
  { id: 57, week: 6, difficulty: 'medium', question: "What is a phishing attack in crypto?", options: ["A fishing game", "Tricking users into revealing keys/approving malicious transactions", "A DeFi strategy", "A mining technique"], answer: "Tricking users into revealing keys/approving malicious transactions", explanation: "Phishing attacks impersonate legitimate sites or use fake airdrops to trick users into signing malicious transactions or revealing private keys. Always verify URLs!" },
  { id: 58, week: 6, difficulty: 'easy', question: "What should you NEVER do with your private key or seed phrase?", options: ["Write it down", "Store it offline", "Share it with anyone online or in DMs", "Memorize it"], answer: "Share it with anyone online or in DMs", explanation: "NEVER share your private key or seed phrase with ANYONE, even if they claim to be support staff. No legitimate service will ever ask for these." },
  { id: 59, week: 6, difficulty: 'medium', question: "What is a token approval and why is it risky?", options: ["Buying tokens", "Permission you give a smart contract to spend your tokens", "Creating tokens", "Burning tokens"], answer: "Permission you give a smart contract to spend your tokens", explanation: "Token approvals let smart contracts spend your tokens. Unlimited approvals on malicious contracts can drain all your tokens. Use revoke.cash to manage approvals." },
  { id: 60, week: 6, difficulty: 'hard', question: "What is a rug pull?", options: ["A DeFi innovation", "A scam where developers abandon a project and take investors' funds", "A new consensus mechanism", "A trading strategy"], answer: "A scam where developers abandon a project and take investors' funds", explanation: "A rug pull is a crypto scam where project creators drain liquidity or abandon the project after raising funds. Always DYOR (Do Your Own Research) before investing." },

  // ═══ WEEK 7: Onchain Identity & Social ═══
  { id: 61, week: 7, difficulty: 'easy', question: "What is an ENS name?", options: ["An email address", "A human-readable name for Ethereum addresses (like 'vitalik.eth')", "A social media handle", "A API endpoint"], answer: "A human-readable name for Ethereum addresses (like 'vitalik.eth')", explanation: "ENS (Ethereum Name Service) maps human-readable names to Ethereum addresses. Instead of '0x1234...', you can use 'name.eth' to receive crypto." },
  { id: 62, week: 7, difficulty: 'medium', question: "What is onchain identity?", options: ["A government ID", "Your verifiable digital identity built from blockchain activity", "A KYC process", "A social security number"], answer: "Your verifiable digital identity built from blockchain activity", explanation: "Onchain identity is your reputation and identity built from your blockchain activity — tokens held, protocols used, NFTs minted, and attestations received." },
  { id: 63, week: 7, difficulty: 'easy', question: "What is a dApp?", options: ["A phone app", "A decentralized application running on blockchain", "A database app", "A desktop application"], answer: "A decentralized application running on blockchain", explanation: "A dApp (decentralized application) runs on a blockchain network rather than centralized servers. dApps on Base include DEXs, social platforms, games, and more." },
  { id: 64, week: 7, difficulty: 'medium', question: "What are attestations in the onchain identity context?", options: ["Certificates", "Onchain claims or verifications about an address/entity", "Transactions", "Token transfers"], answer: "Onchain claims or verifications about an address/entity", explanation: "Attestations are onchain statements/proofs about an identity (e.g., 'this address completed a course' or 'this entity is verified'). The Ethereum Attestation Service (EAS) enables this." },
  { id: 65, week: 7, difficulty: 'hard', question: "What is a Soulbound Token (SBT)?", options: ["A transferable NFT", "A non-transferable token that represents identity or credentials", "A governance token", "A stablecoin"], answer: "A non-transferable token that represents identity or credentials", explanation: "Soulbound Tokens (SBTs) are non-transferable NFTs that represent credentials, achievements, or identity. They can't be sold or transferred, ensuring authentic reputation." },
  { id: 66, week: 7, difficulty: 'easy', question: "What is Warpcast?", options: ["A streaming service", "The leading client app for the Farcaster protocol", "A DEX", "A bridge"], answer: "The leading client app for the Farcaster protocol", explanation: "Warpcast is the most popular client application for the Farcaster decentralized social protocol, where many Base community members interact and share updates." },
  { id: 67, week: 7, difficulty: 'medium', question: "What are Frames on Farcaster?", options: ["Picture frames", "Interactive mini-apps embedded in Farcaster posts", "Browser extensions", "Smart contracts"], answer: "Interactive mini-apps embedded in Farcaster posts", explanation: "Frames are interactive experiences embedded directly in Farcaster posts. They can include games, polls, NFT mints, and transactions — all without leaving the feed." },
  { id: 68, week: 7, difficulty: 'medium', question: "What is a Farcaster FID?", options: ["A Financial ID", "A unique numerical identifier for a Farcaster user", "A token ticker", "A smart contract address"], answer: "A unique numerical identifier for a Farcaster user", explanation: "Every Farcaster user gets a unique FID (Farcaster ID) — a numerical identifier stored onchain. Lower FIDs indicate earlier adoption of the protocol." },
  { id: 69, week: 7, difficulty: 'hard', question: "What is onchain reputation?", options: ["Social media followers", "A trustworthiness score derived from verifiable blockchain activity", "Number of tokens held", "Credit score"], answer: "A trustworthiness score derived from verifiable blockchain activity", explanation: "Onchain reputation is earned through verifiable blockchain interactions — protocol usage, governance participation, attestations, and community contributions." },
  { id: 70, week: 7, difficulty: 'easy', question: "What does 'Based' mean in Base community culture?", options: ["Located at a base", "Aligned with and building on the Base ecosystem", "A meme coin", "A staking method"], answer: "Aligned with and building on the Base ecosystem", explanation: "'Based' is a cultural term in the Base community meaning someone or something is aligned with and actively contributing to the Base ecosystem." },

  // ═══ WEEK 8: Bridging & Cross-Chain ═══
  { id: 71, week: 8, difficulty: 'easy', question: "What is bridging in crypto?", options: ["Building physical bridges", "Moving assets between different blockchain networks", "Creating connections between wallets", "Mining on multiple chains"], answer: "Moving assets between different blockchain networks", explanation: "Bridging is the process of transferring crypto assets from one blockchain to another (e.g., from Ethereum to Base, or from Solana to Base)." },
  { id: 72, week: 8, difficulty: 'medium', question: "How long does an official L1→Base bridge withdrawal take?", options: ["Instant", "About 7 days (challenge period)", "1 hour", "24 hours"], answer: "About 7 days (challenge period)", explanation: "Official optimistic rollup withdrawals from Base to Ethereum L1 take about 7 days due to the fraud proof challenge period. Third-party bridges can be faster." },
  { id: 73, week: 8, difficulty: 'medium', question: "What is a canonical bridge?", options: ["A church bridge", "The official, protocol-level bridge between L1 and L2", "Any third-party bridge", "A centralized exchange"], answer: "The official, protocol-level bridge between L1 and L2", explanation: "The canonical bridge is the official, trust-minimized bridge built into the rollup protocol itself. Base's canonical bridge inherits the full security of the rollup." },
  { id: 74, week: 8, difficulty: 'easy', question: "Can you bridge from Solana to Base?", options: ["No, it's impossible", "Yes, using cross-chain bridge protocols", "Only through Coinbase", "Only with Bitcoin"], answer: "Yes, using cross-chain bridge protocols", explanation: "You can bridge assets from Solana to Base using cross-chain protocols like Wormhole, deBridge, or Mayan Finance. Base now has a dedicated Solana bridge." },
  { id: 75, week: 8, difficulty: 'hard', question: "What is the fraud proof mechanism?", options: ["A security camera", "A system where anyone can challenge invalid L2 transactions on L1", "A KYC system", "Anti-phishing software"], answer: "A system where anyone can challenge invalid L2 transactions on L1", explanation: "In optimistic rollups like Base, transactions are assumed valid (optimistic). Anyone can submit a fraud proof during the challenge period if they detect invalid state transitions." },
  { id: 76, week: 8, difficulty: 'medium', question: "What is cross-chain messaging?", options: ["Sending text messages", "Smart contracts on different chains communicating with each other", "Email between users", "Chat protocol"], answer: "Smart contracts on different chains communicating with each other", explanation: "Cross-chain messaging allows smart contracts on different blockchains to send messages and trigger actions on each other, enabling interoperable dApp experiences." },
  { id: 77, week: 8, difficulty: 'easy', question: "What are wrapped tokens?", options: ["Gift tokens", "Tokens representing assets from another chain (e.g., WETH)", "Encrypted tokens", "Deleted tokens"], answer: "Tokens representing assets from another chain (e.g., WETH)", explanation: "Wrapped tokens are tokens on one chain that represent assets from another chain. WETH (Wrapped Ether) and wrapped BTC are common examples used across DeFi." },
  { id: 78, week: 8, difficulty: 'hard', question: "What is data availability in the context of rollups?", options: ["Data backups", "Ensuring L2 transaction data is accessible for verification on L1", "Database storage", "Cloud hosting"], answer: "Ensuring L2 transaction data is accessible for verification on L1", explanation: "Data availability ensures that the data needed to verify L2 transactions is posted to and accessible on L1 (Ethereum), so anyone can verify the rollup's state." },
  { id: 79, week: 8, difficulty: 'medium', question: "What is a third-party bridge?", options: ["An unauthorized bridge", "A non-canonical bridge service offering faster/cheaper bridging", "A government bridge", "A broken bridge"], answer: "A non-canonical bridge service offering faster/cheaper bridging", explanation: "Third-party bridges like Across Protocol, Stargate, and Hop offer faster bridging (often instant) compared to the 7-day canonical withdrawal, though with different trust assumptions." },
  { id: 80, week: 8, difficulty: 'easy', question: "What should you check before using a bridge?", options: ["The weather", "Contract audits, supported tokens, fees, and trustworthiness", "The blockchain's age", "Number of validators"], answer: "Contract audits, supported tokens, fees, and trustworthiness", explanation: "Before bridging, always verify the bridge has been audited, check the supported tokens and fees, and confirm you're on the official URL. Bridge exploits are common." },

  // ═══ WEEK 9: Building on Base ═══
  { id: 81, week: 9, difficulty: 'easy', question: "What is an RPC endpoint?", options: ["A website URL", "A gateway to communicate with a blockchain node", "An email server", "A mining pool"], answer: "A gateway to communicate with a blockchain node", explanation: "RPC (Remote Procedure Call) endpoints allow your dApp to send transactions and read data from Base. Services like Alchemy, Infura, and QuickNode provide reliable RPCs." },
  { id: 82, week: 9, difficulty: 'medium', question: "What is OnchainKit?", options: ["A physical toolkit", "Coinbase's SDK for building onchain applications on Base", "A hardware wallet", "A mining rig"], answer: "Coinbase's SDK for building onchain applications on Base", explanation: "OnchainKit is a collection of React components and utilities by Coinbase that helps developers quickly build onchain applications on Base with features like wallet connection and transactions." },
  { id: 83, week: 9, difficulty: 'medium', question: "What is wagmi?", options: ["An acronym meaning 'We're all gonna make it'", "Both a crypto saying AND a popular React hooks library for Ethereum", "A DeFi protocol", "A blockchain"], answer: "Both a crypto saying AND a popular React hooks library for Ethereum", explanation: "WAGMI ('We're all gonna make it') is both a crypto cultural phrase AND the name of a popular React hooks library used to interact with Ethereum wallets and Base." },
  { id: 84, week: 9, difficulty: 'easy', question: "What is viem?", options: ["A video platform", "A TypeScript library for interacting with Ethereum/Base", "A social media app", "A wallet"], answer: "A TypeScript library for interacting with Ethereum/Base", explanation: "viem is a lightweight, type-safe TypeScript library for interacting with Ethereum and L2s like Base. It's the backbone used by wagmi for low-level blockchain interactions." },
  { id: 85, week: 9, difficulty: 'hard', question: "What is Base's rollup architecture?", options: ["Single-chain architecture", "Sequencer posts batched transactions to L1 Ethereum", "Peer-to-peer mining", "Sharding"], answer: "Sequencer posts batched transactions to L1 Ethereum", explanation: "Base's sequencer collects transactions, orders them, and posts compressed batches to Ethereum L1. This provides L1 security while enabling fast, cheap L2 transactions." },
  { id: 86, week: 9, difficulty: 'medium', question: "What are Base builder rewards?", options: ["Salary from Coinbase", "Financial incentives for developers building on Base", "Mining rewards", "Staking yields"], answer: "Financial incentives for developers building on Base", explanation: "Base offers builder rewards and grants to incentivize developers to build applications on the network. Programs include builder score rewards, grants, and retroactive funding." },
  { id: 87, week: 9, difficulty: 'easy', question: "What is the Base Sepolia faucet?", options: ["A water fountain", "A service that provides free testnet ETH for development", "A DeFi protocol", "A bridge"], answer: "A service that provides free testnet ETH for development", explanation: "The Base Sepolia faucet provides free testnet ETH to developers so they can test their smart contracts and dApps without spending real money." },
  { id: 88, week: 9, difficulty: 'medium', question: "What is Foundry's 'forge' tool used for?", options: ["Metalworking", "Compiling, testing, and deploying Solidity smart contracts", "Creating wallets", "Mining tokens"], answer: "Compiling, testing, and deploying Solidity smart contracts", explanation: "Forge is Foundry's core tool for compiling Solidity, running tests (in Solidity!), and deploying contracts. It's known for its speed and developer experience." },
  { id: 89, week: 9, difficulty: 'hard', question: "What is a paymaster in Base/ERC-4337?", options: ["An accountant", "A contract that sponsors gas fees for user transactions", "A validator", "A token"], answer: "A contract that sponsors gas fees for user transactions", explanation: "A paymaster is a smart contract that pays gas fees on behalf of users, enabling gasless transactions. This removes one of the biggest UX barriers in crypto." },
  { id: 90, week: 9, difficulty: 'medium', question: "What is ABI in smart contract development?", options: ["A blockchain ID", "Application Binary Interface — defines how to interact with a contract", "A token type", "An API key"], answer: "Application Binary Interface — defines how to interact with a contract", explanation: "ABI defines the methods and data structures of a smart contract. Frontend apps use the ABI to encode function calls and decode return values when interacting with contracts." },

  // ═══ WEEK 10: Base Future & Advanced ═══
  { id: 91, week: 10, difficulty: 'easy', question: "What is Base's vision for the future?", options: ["Replace Bitcoin", "Bring the next billion users onchain", "Create a new internet", "Replace banks"], answer: "Bring the next billion users onchain", explanation: "Base's mission is to bring the next billion users onchain by making blockchain technology accessible, affordable, and useful for everyday people and developers." },
  { id: 92, week: 10, difficulty: 'medium', question: "What role do AI agents play in the Base ecosystem?", options: ["They mine crypto", "Autonomous AI programs that transact and interact onchain", "They write blog posts", "They validate transactions"], answer: "Autonomous AI programs that transact and interact onchain", explanation: "AI agents on Base are autonomous programs that can hold wallets, make transactions, and interact with smart contracts. Base provides infrastructure for giving agents onchain identities." },
  { id: 93, week: 10, difficulty: 'hard', question: "What is the OP Stack fault proof system?", options: ["A debugging tool", "A mechanism allowing permissionless validation of L2 state on L1", "A backup system", "A consensus algorithm"], answer: "A mechanism allowing permissionless validation of L2 state on L1", explanation: "The fault proof system allows anyone to challenge invalid state roots posted by the sequencer. It's a critical security mechanism that enables trust-minimized L2 operation." },
  { id: 94, week: 10, difficulty: 'medium', question: "What is the Base ecosystem fund?", options: ["A hedge fund", "A fund to invest in and support projects building on Base", "A charity", "A payroll"], answer: "A fund to invest in and support projects building on Base", explanation: "The Base ecosystem fund provides capital, resources, and support to promising projects and builders in the Base ecosystem, accelerating growth and innovation." },
  { id: 95, week: 10, difficulty: 'hard', question: "What is sequencer decentralization?", options: ["Multiple exchanges", "Distributing the sequencer role among multiple operators", "More mining pools", "Token distribution"], answer: "Distributing the sequencer role among multiple operators", explanation: "Sequencer decentralization aims to distribute the transaction ordering role among multiple independent operators, reducing centralization risk and increasing censorship resistance." },
  { id: 96, week: 10, difficulty: 'medium', question: "What is a multisig wallet?", options: ["A wallet for multiple coins", "A wallet requiring multiple signatures to approve transactions", "A backup wallet", "A cold wallet"], answer: "A wallet requiring multiple signatures to approve transactions", explanation: "Multisig wallets require M-of-N signatures (e.g., 3 of 5 keyholders) to authorize transactions. They're essential for DAOs, treasuries, and organizational security." },
  { id: 97, week: 10, difficulty: 'easy', question: "What is a DAO?", options: ["A database", "Decentralized Autonomous Organization — community-governed entity", "A type of coin", "A blockchain"], answer: "Decentralized Autonomous Organization — community-governed entity", explanation: "A DAO is an organization governed by smart contracts and community votes rather than traditional management. Many projects on Base use DAO governance for decision-making." },
  { id: 98, week: 10, difficulty: 'hard', question: "What is EIP-1559 and how does it affect Base fees?", options: ["A token standard", "A fee mechanism with base fee + tip that enables fee predictability", "A mining algorithm", "A scaling solution"], answer: "A fee mechanism with base fee + tip that enables fee predictability", explanation: "EIP-1559 splits gas fees into a base fee (burned) and priority fee (tip). This makes gas fees more predictable and reduces fee spikes during congestion." },
  { id: 99, week: 10, difficulty: 'medium', question: "What is Base's approach to onchain payments?", options: ["Bitcoin payments", "Low-cost USDC-based payments with fast finality", "Credit card processing", "Wire transfers"], answer: "Low-cost USDC-based payments with fast finality", explanation: "Base enables fast, cheap payments using USDC and other tokens. With sub-cent fees and near-instant confirmation, Base is becoming a practical payment rail." },
  { id: 100, week: 10, difficulty: 'easy', question: "How can you stay updated with Base developments?", options: ["Newspaper", "Follow base.org, @base on X/Farcaster, and join the community", "Television", "Radio"], answer: "Follow base.org, @base on X/Farcaster, and join the community", explanation: "Stay updated by visiting base.org, following @base on X (Twitter) and Farcaster, joining the Base Discord, and reading the Base blog at blog.base.dev." },
];

export const WEEK_THEMES = [
  { week: 1, title: "Base Fundamentals", emoji: "🔵", description: "Core concepts of Base chain" },
  { week: 2, title: "Ecosystem & DApps", emoji: "🌐", description: "Explore the Base ecosystem" },
  { week: 3, title: "Smart Contracts", emoji: "📝", description: "Building on Base" },
  { week: 4, title: "DeFi on Base", emoji: "💰", description: "Decentralized Finance" },
  { week: 5, title: "NFTs & Assets", emoji: "🎨", description: "Digital ownership" },
  { week: 6, title: "Wallets & Security", emoji: "🔐", description: "Staying safe onchain" },
  { week: 7, title: "Identity & Social", emoji: "👤", description: "Onchain identity" },
  { week: 8, title: "Bridging & Cross-Chain", emoji: "🌉", description: "Moving assets across chains" },
  { week: 9, title: "Building on Base", emoji: "⚒️", description: "Developer tools & SDKs" },
  { week: 10, title: "Future & Advanced", emoji: "🚀", description: "What's next for Base" },
];

// ── Week System: 7 days per week in real time ──
// Setting start date exactly 7 days before tonight's midnight to extend Week 1
export const WEEK_START_DATE = new Date('2026-04-02T00:00:00+05:00'); 

// Get the current active week number (1-10)
export function getCurrentWeek(): number {
  const now = new Date();
  const diffMs = now.getTime() - WEEK_START_DATE.getTime();
  if (diffMs < 0) return 1; // Before start → Week 1
  const weekIndex = Math.floor(diffMs / (7 * 24 * 60 * 60 * 1000));
  return Math.min(weekIndex + 1, 10); // Cap at 10
}

// Check if a specific week is currently "live" (its 7-day window)
export function isWeekActive(week: number): boolean {
  const now = new Date();
  const weekStart = getWeekStartDate(week);
  const weekEnd = new Date(weekStart.getTime() + 7 * 24 * 60 * 60 * 1000);
  return now >= weekStart && now < weekEnd;
}

// Get the start date of a specific week
export function getWeekStartDate(week: number): Date {
  return new Date(WEEK_START_DATE.getTime() + (week - 1) * 7 * 24 * 60 * 60 * 1000);
}

// Get the end date of a specific week
export function getWeekEndDate(week: number): Date {
  return new Date(WEEK_START_DATE.getTime() + week * 7 * 24 * 60 * 60 * 1000);
}

// Check if a week has been unlocked (all previous weeks must be completed)
export function isWeekUnlocked(week: number, completedWeeks: Record<number, number>): boolean {
  if (week === 1) return true;
  // Unlock if previous week is completed and current time has reached this week
  return completedWeeks[week - 1] !== undefined && getCurrentWeek() >= week;
}

// Get days remaining in the current week
export function getDaysRemaining(week: number): number {
  const now = new Date();
  const weekEnd = getWeekEndDate(week);
  const diff = weekEnd.getTime() - now.getTime();
  return Math.max(0, Math.ceil(diff / (24 * 60 * 60 * 1000)));
}

// Format date for display
export function formatWeekDates(week: number): string {
  const start = getWeekStartDate(week);
  const end = new Date(getWeekEndDate(week).getTime() - 1); // -1ms to show last day
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' };
  return `${start.toLocaleDateString('en-US', opts)} – ${end.toLocaleDateString('en-US', opts)}`;
}

export function getQuizByWeek(week: number): BaseQuizQuestion[] {
  return BASE_QUIZ_DATA.filter(q => q.week === week);
}
