export type QuizQuestion = {
  level: number;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
};

export const QUIZ_DATA: QuizQuestion[] = [
  // Level 1: Basics (10 questions)
  { level: 1, question: "What keyword declares a block-scoped variable?", options: ["var", "let", "const", "int"], answer: "let", explanation: "Think of `let` as a way to name something that only lives inside its own local code block. It's great because it doesn't leak out and cause bugs elsewhere!" },
  { level: 1, question: "What will `typeof []` return?", options: ["array", "object", "list", "undefined"], answer: "object", explanation: "In JavaScript, almost everything is an object under the hood, even arrays! That's why `typeof []` gives you 'object'." },
  { level: 1, question: "Which method adds an element to the END of an array?", options: ["shift()", "unshift()", "push()", "pop()"], answer: "push()", explanation: "Imagine you're adding something to the back of a line—that's exactly what `push()` does to an array." },
  { level: 1, question: "Which method removes the first element of an array?", options: ["shift()", "unshift()", "pop()", "splice()"], answer: "shift()", explanation: "When the first person in line leaves, everyone shifts forward. That's why the method to remove the first item is called `shift()`." },
  { level: 1, question: "How do you write a comment in JavaScript?", options: ["// comment", "/* comment */", "# comment", "Both // and /* */"], answer: "Both // and /* */", explanation: "You can use `//` for a quick one-liner or `/* */` if you've got a lot to say across multiple lines. Both are perfectly fine!" },
  { level: 1, question: "Which symbol is used for strict equality?", options: ["=", "==", "===", "!="], answer: "===", explanation: "The triple equals `===` is like a super-strict judge. It checks both the value and the type to make sure they're exactly the same." },
  { level: 1, question: "How do you declare a constant?", options: ["let", "const", "var", "constant"], answer: "const", explanation: "Use `const` when you want to lock a value in. Once you set it, you can't change the name to point to something else." },
  { level: 1, question: "Which method converts a JSON string into an object?", options: ["JSON.parse()", "JSON.stringify()", "JSON.convert()", "JSON.toObject()"], answer: "JSON.parse()", explanation: "When you get data from the web as a string, `JSON.parse()` reads (parses) it and turns it into a real JavaScript object you can use." },
  { level: 1, question: "Which function adds an element to the BEGINNING of an array?", options: ["push()", "unshift()", "shift()", "pop()"], answer: "unshift()", explanation: "It's a bit of a weird name, but `unshift()` is what you use to squeeze a new item right into the very front of your array." },
  { level: 1, question: "What is the result of `2 + '2'`?", options: ["4", "'22'", "NaN", "'4'"], answer: "'22'", explanation: "JavaScript sees you're adding a number to a string and decides to just stick them together (concatenation), resulting in the string '22'." },

  // Level 2: Functions (10 questions)
  { level: 2, question: "What is the difference between function declaration and function expression?", options: ["No difference", "Declaration is hoisted, expression is not", "Expression is faster", "Declaration is faster"], answer: "Declaration is hoisted, expression is not", explanation: "Function declarations are 'hoisted' to the top, meaning you can call them even before they appear in your code. Expressions aren't that eager!" },
  { level: 2, question: "What does the return statement do?", options: ["Exits the function and returns a value", "Only exits the function", "Only returns a value", "Prints the value"], answer: "Exits the function and returns a value", explanation: "Think of `return` as the exit door. It stops the function and hands back whatever result you've calculated." },
  { level: 2, question: "What is a callback function?", options: ["A function called after an event", "A function that calls itself", "A function with no parameters", "A function inside an object"], answer: "A function called after an event", explanation: "It's like leaving a 'call me back' message. You pass a function as an argument, and it gets executed later when something else finishes." },
  { level: 2, question: "What is a closure?", options: ["A function that returns another function", "A function with access to outer scope variables", "A function that can't be modified", "A function without parameters"], answer: "A function with access to outer scope variables", explanation: "A closure is like a function with a memory. It remembers the variables that were around when it was first created, even after its parent function finishes." },
  { level: 2, question: "What is the 'this' keyword?", options: ["A reference to the current object", "A loop keyword", "A conditional keyword", "A variable declaration"], answer: "A reference to the current object", explanation: "`this` is like a self-referencing pronoun. It points to the object that is currently executing the code." },
  { level: 2, question: "What is an arrow function?", options: ["() => {}", "function() {}", "-> function", "=>function"], answer: "() => {}", explanation: "Introduced in ES6, arrow functions give us a much shorter syntax. They also handle the `this` keyword a bit differently than regular functions." },
  { level: 2, question: "What does the spread operator (...) do?", options: ["Repeats code", "Expands an iterable into individual elements", "Creates a copy of code", "Connects functions"], answer: "Expands an iterable into individual elements", explanation: "The `...` operator 'spills' all the items from an array or object into a new one. It's super handy for making copies or merging things." },
  { level: 2, question: "What is destructuring?", options: ["Breaking down objects or arrays", "Deleting properties", "Combining objects", "Cloning arrays"], answer: "Breaking down objects or arrays", explanation: "Destructuring is a clean way to 'unpack' values from arrays or properties from objects directly into distinct variables." },
  { level: 2, question: "What is a pure function?", options: ["A function with no side effects", "A function in pure JavaScript", "A function without parameters", "A function that returns undefined"], answer: "A function with no side effects", explanation: "A pure function is predictable. Given the same input, it always gives the same output and doesn't mess with anything outside itself." },
  { level: 2, question: "What is recursion?", options: ["A function that calls itself", "Repeating code", "Looping through arrays", "Cloning objects"], answer: "A function that calls itself", explanation: "Recursion is when a function calls itself to solve a smaller piece of the same problem. Just make sure it has a way to stop!" },

  // Level 3: Objects & Prototypes (10 questions)
  { level: 3, question: "How do you create an object in JavaScript?", options: ["{}", "new Object()", "Object.create()", "All of the above"], answer: "All of the above", explanation: "You've got options! Whether you use the curly braces `{}`, the `new` keyword, or `Object.create()`, you're successfully making a new object." },
  { level: 3, question: "What is a prototype?", options: ["A template for objects", "A function", "An array", "A string"], answer: "A template for objects", explanation: "Prototypes are like the 'DNA' or a shared template. They allow objects to inherit properties and methods from other objects." },
  { level: 3, question: "What is the difference between == and ===?", options: ["No difference", "== checks type, === checks value", "=== checks type and value, == only checks value", "== is faster"], answer: "=== checks type and value, == only checks value", explanation: "Loose equality `==` tries to be helpful by converting types, but strict equality `===` is much safer because it demands an exact match in both value and type." },
  { level: 3, question: "What is Object.keys() used for?", options: ["Returns array of object keys", "Deletes keys", "Counts keys", "Finds a key"], answer: "Returns array of object keys", explanation: "If you want a list of all the property names (keys) inside an object, `Object.keys()` will gather them all up into a nice array for you." },
  { level: 3, question: "What is the purpose of Object.assign()?", options: ["Copies properties from one object to another", "Deletes objects", "Merges arrays", "Creates a new object"], answer: "Copies properties from one object to another", explanation: "`Object.assign()` is like a copier. It takes properties from one or more source objects and pastes them into a target object." },
  { level: 3, question: "What is a constructor function?", options: ["A function that creates objects", "A function that constructs HTML", "A function in a class", "A function that returns values"], answer: "A function that creates objects", explanation: "Think of a constructor as a factory function. When you call it with `new`, it stamps out a brand new object based on the instructions you wrote." },
  { level: 3, question: "What does Object.create() do?", options: ["Creates a new object with a specified prototype", "Creates a copy of an object", "Deletes an object", "Merges objects"], answer: "Creates a new object with a specified prototype", explanation: "This method lets you pick exactly which 'template' (prototype) your new object should follow right from the start." },
  { level: 3, question: "What is the difference between undefined and null?", options: ["No difference", "undefined is unintentional, null is intentional", "null is faster", "undefined is an object"], answer: "undefined is unintentional, null is intentional", explanation: "`undefined` usually means JavaScript hasn't given a value yet, while `null` is a value *you* explicitly set to say 'this is empty'." },
  { level: 3, question: "What is a property descriptor?", options: ["Describes properties of an object", "A string describing objects", "A function", "An array of properties"], answer: "Describes properties of an object", explanation: "Under the hood, every property has settings (like if it can be changed or deleted). These settings are what we call property descriptors." },
  { level: 3, question: "What is Object.freeze() used for?", options: ["Prevents modifications to an object", "Clones an object", "Creates a prototype", "Merges objects"], answer: "Prevents modifications to an object", explanation: "As the name suggests, `Object.freeze()` locks an object down. No new properties can be added, and current ones can't be changed or deleted." },

  // Level 4: Arrays & Higher-Order Functions (10 questions)
  { level: 4, question: "What does Array.map() do?", options: ["Transforms each element", "Finds an element", "Removes elements", "Counts elements"], answer: "Transforms each element", explanation: "Think of `map()` as a transformer. It goes through every item in your array, does something to it, and gives you a brand new array with the results." },
  { level: 4, question: "What is Array.filter() used for?", options: ["Removes elements that don't match a condition", "Adds elements", "Sorts arrays", "Counts elements"], answer: "Removes elements that don't match a condition", explanation: "Just like a coffee filter, `filter()` only lets the items that pass your specific test through into a new array." },
  { level: 4, question: "What does Array.reduce() do?", options: ["Reduces array to a single value", "Removes elements", "Sorts arrays", "Counts elements"], answer: "Reduces array to a single value", explanation: "`reduce()` is like a snow-ball. It rolls through the array, accumulating values into one final result (like a sum or a single object)." },
  { level: 4, question: "What is Array.find() used for?", options: ["Finds first element matching condition", "Counts matching elements", "Removes elements", "Sorts arrays"], answer: "Finds first element matching condition", explanation: "When you just need the very first item that matches your criteria, `find()` is your best friend. It stops searching as soon as it finds a match!" },
  { level: 4, question: "What is Array.some() used for?", options: ["Tests if any element passes a condition", "Counts elements", "Finds elements", "Sorts arrays"], answer: "Tests if any element passes a condition", explanation: "`some()` is an optimist. It returns `true` if it finds at least *one* item that matches your condition." },
  { level: 4, question: "What is Array.every() used for?", options: ["Tests if all elements pass a condition", "Counts elements", "Finds elements", "Removes elements"], answer: "Tests if all elements pass a condition", explanation: "`every()` is a perfectionist. It only returns `true` if *every single item* in the array passed your test." },
  { level: 4, question: "What is Array.includes() used for?", options: ["Checks if array contains a value", "Adds values", "Removes values", "Counts values"], answer: "Checks if array contains a value", explanation: "It's a simple yes/no question: 'Hey array, do you have this specific value inside you?'" },
  { level: 4, question: "What is Array.join() used for?", options: ["Joins array elements into a string", "Merges arrays", "Separates arrays", "Counts elements"], answer: "Joins array elements into a string", explanation: "`join()` takes all the separate pieces in your array and glues them together into one long string, using whatever separator you like." },
  { level: 4, question: "What is Array.slice() used for?", options: ["Returns a shallow copy of a portion", "Removes elements", "Adds elements", "Sorts arrays"], answer: "Returns a shallow copy of a portion", explanation: "Like taking a slice of pizza, `slice()` gives you a new array containing a portion of the original, without changing the original at all." },
  { level: 4, question: "What is Array.splice() used for?", options: ["Removes and/or adds elements", "Finds elements", "Copies arrays", "Sorts arrays"], answer: "Removes and/or adds elements", explanation: "`splice()` is more invasive. It can cut items out of an array or stitch new ones in, modifying the original array directly." },

  // Level 5: Async & Promises (10 questions)
  { level: 5, question: "What is a Promise?", options: ["An object representing async operation", "A function", "An array", "A string"], answer: "An object representing async operation", explanation: "A Promise is like a real-life promise: 'I'll get back to you later with a result or an error.' It's how we handle things that take time, like fetching data." },
  { level: 5, question: "What are the states of a Promise?", options: ["pending, fulfilled, rejected", "start, middle, end", "true, false, null", "open, closed, error"], answer: "pending, fulfilled, rejected", explanation: "It starts as `pending` (waiting), then either becomes `fulfilled` (success!) or `rejected` (something went wrong)." },
  { level: 5, question: "What is async/await?", options: ["Syntactic sugar for Promises", "A loop", "A variable declaration", "A function modifier"], answer: "Syntactic sugar for Promises", explanation: "`async/await` is a beautiful way to write asynchronous code that reads almost like a simple step-by-step list, without all the `.then()` nesting." },
  { level: 5, question: "What does .then() do?", options: ["Handles successful resolution", "Handles errors", "Creates a loop", "Defines a variable"], answer: "Handles successful resolution", explanation: "Think of `.then()` as saying: 'Okay, once the promise is successfully kept, do *this* next bit of work.'" },
  { level: 5, question: "What does .catch() do?", options: ["Handles rejected Promise", "Handles successful Promise", "Creates a loop", "Defines a variable"], answer: "Handles rejected Promise", explanation: "The `.catch()` method is your safety net. It catches any errors or rejections that happen along the way so your app doesn't crash." },
  { level: 5, question: "What is Promise.all() used for?", options: ["Waits for all Promises to resolve", "Stops at first rejection", "Returns first result", "Combines arrays"], answer: "Waits for all Promises to resolve", explanation: "When you have a bunch of things to do at once, `Promise.all()` waits for *everyone* to cross the finish line before moving forward." },
  { level: 5, question: "What is Promise.race() used for?", options: ["Returns first Promise to settle", "Waits for all Promises", "Combines Promises", "Cancels Promises"], answer: "Returns first Promise to settle", explanation: "Just like a real race, the first promise to finish (either success or failure) wins, and the result is returned immediately." },
  { level: 5, question: "What is a callback hell?", options: ["Deeply nested callbacks", "Error in callbacks", "A Promise", "An async function"], answer: "Deeply nested callbacks", explanation: "This is what happens when you nest too many callbacks inside each other. It becomes a messy 'pyramid of doom' that's very hard to read!" },
  { level: 5, question: "What is a microtask queue?", options: ["Queue for Promises and callbacks", "A type of array", "A variable", "A loop structure"], answer: "Queue for Promises and callbacks", explanation: "The microtask queue is like a high-priority lane. Promise resolutions go here to be handled ASAP, before the browser does its next big task." },
  { level: 5, question: "What is event loop?", options: ["Mechanism that executes code, collects events, and processes queued callbacks", "A loop in HTML", "A JavaScript loop", "A type of array"], answer: "Mechanism that executes code, collects events, and processes queued callbacks", explanation: "The event loop is the secret sauce. It's a non-stop manager that checks the call stack and moves tasks from the queue when the stack is empty." },

  // Level 6-10: Continue with similar structure...
  // Level 6: DOM & Events
  { level: 6, question: "What is DOM?", options: ["Document Object Model", "Data Object Model", "Display Object Model", "Dynamic Object Model"], answer: "Document Object Model", explanation: "DOM is a programming interface for HTML and XML documents." },
  { level: 6, question: "How do you select an element by ID?", options: ["document.getElementById()", "document.querySelector()", "document.getElement()", "document.select()"], answer: "document.getElementById()", explanation: "getElementById() returns the element with a specified ID." },
  { level: 6, question: "What is event delegation?", options: ["Handling events on parent element", "Creating multiple event listeners", "Removing event listeners", "Cloning event listeners"], answer: "Handling events on parent element", explanation: "Event delegation uses event bubbling to handle events at parent level." },
  { level: 6, question: "What does preventDefault() do?", options: ["Cancels default behavior", "Prevents element creation", "Stops event propagation", "Removes an element"], answer: "Cancels default behavior", explanation: "preventDefault() prevents the browser's default action for an event." },
  { level: 6, question: "What is event bubbling?", options: ["Event propagates from child to parent", "Event propagates from parent to child", "Event stops at element", "Event duplicates"], answer: "Event propagates from child to parent", explanation: "In event bubbling, events propagate upward through parent elements." },
  { level: 6, question: "What is event capturing?", options: ["Event propagates from parent to child", "Event propagates from child to parent", "Event stops at element", "Event duplicates"], answer: "Event propagates from parent to child", explanation: "In event capturing, events propagate downward from parent to child elements." },
  { level: 6, question: "What is localStorage?", options: ["Stores data locally in browser", "Stores data on server", "Stores data in memory", "Stores data in database"], answer: "Stores data locally in browser", explanation: "localStorage allows storing key-value pairs locally with no expiration." },
  { level: 6, question: "What is sessionStorage?", options: ["Stores data for one session", "Stores data permanently", "Stores data on server", "Stores data in memory"], answer: "Stores data for one session", explanation: "sessionStorage stores data that gets cleared when the tab/window closes." },
  { level: 6, question: "What does querySelectorAll() return?", options: ["NodeList of all matching elements", "Single element", "Array", "String"], answer: "NodeList of all matching elements", explanation: "querySelectorAll() returns a static NodeList of all matching elements." },
  { level: 6, question: "How do you add a class to an element?", options: ["element.classList.add()", "element.addClass()", "element.class.add()", "element.setClass()"], answer: "element.classList.add()", explanation: "classList.add() adds a class name to an element's class list." },

  // Level 7: Error Handling
  { level: 7, question: "What is try/catch used for?", options: ["Handling errors", "Looping", "Conditional logic", "Variable declaration"], answer: "Handling errors", explanation: "try/catch allows catching and handling runtime errors." },
  { level: 7, question: "What is finally block?", options: ["Executes regardless of try/catch result", "Executes only on error", "Executes only on success", "Executes before try"], answer: "Executes regardless of try/catch result", explanation: "finally block always executes whether an exception is thrown or not." },
  { level: 7, question: "What is console.log() used for?", options: ["Printing to console", "Logging errors", "Creating logs", "Storing data"], answer: "Printing to console", explanation: "console.log() outputs a message to the web console." },
  { level: 7, question: "What is typeof operator?", options: ["Returns type of a value", "Compares types", "Converts types", "Defines types"], answer: "Returns type of a value", explanation: "typeof returns a string indicating the type of the unevaluated operand." },
  { level: 7, question: "What is instanceof operator?", options: ["Checks if object is instance of a class", "Checks type", "Compares values", "Converts values"], answer: "Checks if object is instance of a class", explanation: "instanceof checks whether an object is an instance of a specific class." },
  { level: 7, question: "What is NaN?", options: ["Not a Number", "Null and Nothing", "Null or NaN", "Number and None"], answer: "Not a Number", explanation: "NaN is a value representing an undefined or unrepresentable mathematical result." },
  { level: 7, question: "What is a stack trace?", options: ["Shows function call sequence leading to error", "Stores variables", "A data structure", "A list of errors"], answer: "Shows function call sequence leading to error", explanation: "A stack trace shows the sequence of function calls that led to an error." },
  { level: 7, question: "What is console.error() used for?", options: ["Logging errors to console", "Throwing errors", "Catching errors", "Printing messages"], answer: "Logging errors to console", explanation: "console.error() logs error messages to the console." },
  { level: 7, question: "What is a breakpoint?", options: ["A point in code where execution pauses", "An error", "A function", "A variable"], answer: "A point in code where execution pauses", explanation: "A breakpoint pauses code execution for debugging purposes." },
  { level: 7, question: "What is the difference between error and exception?", options: ["Error is a condition, exception is thrown", "No difference", "Exception is more severe", "Error is worse"], answer: "Error is a condition, exception is thrown", explanation: "An error is a condition, an exception is when an error is thrown." },

  // Level 8: Classes & OOP
  { level: 8, question: "What is a class?", options: ["Blueprint for creating objects", "A function", "A variable", "An array"], answer: "Blueprint for creating objects", explanation: "Classes are blueprints for creating objects with properties and methods." },
  { level: 8, question: "What is inheritance?", options: ["Child class inherits from parent class", "Creating new variables", "Copying code", "Merging objects"], answer: "Child class inherits from parent class", explanation: "Inheritance allows a child class to inherit properties from a parent class." },
  { level: 8, question: "What is a constructor?", options: ["Method called when creating an object", "A function", "A loop", "A variable"], answer: "Method called when creating an object", explanation: "A constructor is a special method called when an object is created." },
  { level: 8, question: "What is super keyword?", options: ["Calls parent class method", "Defines a function", "Creates a variable", "Imports a module"], answer: "Calls parent class method", explanation: "super allows calling methods of the parent class from a child class." },
  { level: 8, question: "What are static methods?", options: ["Methods called on class, not instance", "Methods that don't change", "Methods with no parameters", "Methods that return nothing"], answer: "Methods called on class, not instance", explanation: "Static methods belong to the class itself, not to instances of the class." },
  { level: 8, question: "What are getters and setters?", options: ["Methods to get/set property values", "Functions", "Variables", "Arrays"], answer: "Methods to get/set property values", explanation: "Getters and setters allow controlled access to object properties." },
  { level: 8, question: "What is the extends keyword?", options: ["Creates inheritance relationship", "Extends a function", "Defines a variable", "Imports a module"], answer: "Creates inheritance relationship", explanation: "extends is used to create a child class that inherits from a parent class." },
  { level: 8, question: "What is method overriding?", options: ["Child class redefines parent method", "Creating multiple methods", "Deleting methods", "Copying methods"], answer: "Child class redefines parent method", explanation: "Method overriding allows a child class to provide a specific implementation of a parent method." },
  { level: 8, question: "What is encapsulation?", options: ["Bundling data and methods together", "Hiding code", "Creating objects", "Defining variables"], answer: "Bundling data and methods together", explanation: "Encapsulation bundles data (variables) and methods into a single unit." },
  { level: 8, question: "What is polymorphism?", options: ["Many forms of the same method", "Creating objects", "Inheriting properties", "Defining variables"], answer: "Many forms of the same method", explanation: "Polymorphism allows objects to take on multiple forms." },

  // Level 9: Advanced Concepts
  { level: 9, question: "What is hoisting?", options: ["Moving declarations to top of scope", "Lifting elements", "Raising values", "Creating variables"], answer: "Moving declarations to top of scope", explanation: "Hoisting is JavaScript's behavior of moving declarations to the top of scope." },
  { level: 9, question: "What is currying?", options: ["Converting function to series of functions", "Adding spice to code", "Creating loops", "Defining variables"], answer: "Converting function to series of functions", explanation: "Currying transforms a function taking multiple arguments into a series of functions." },
  { level: 9, question: "What is memoization?", options: ["Caching function results", "Creating memories", "Storing data", "Managing memory"], answer: "Caching function results", explanation: "Memoization caches results of expensive function calls to improve performance." },
  { level: 9, question: "What is throttling?", options: ["Limiting function calls in time period", "Speeding up code", "Slowing down code", "Creating delays"], answer: "Limiting function calls in time period", explanation: "Throttling limits how often a function can be called." },
  { level: 9, question: "What is debouncing?", options: ["Delaying function call until after events stop", "Removing bugs", "Creating delays", "Stopping events"], answer: "Delaying function call until after events stop", explanation: "Debouncing delays function execution until after a period of inactivity." },
  { level: 9, question: "What is the module pattern?", options: ["Creating private and public scopes", "Defining modules", "Creating files", "Organizing code"], answer: "Creating private and public scopes", explanation: "The module pattern uses closures to create private and public methods." },
  { level: 9, question: "What is WeakMap?", options: ["Map with weak key references", "A type of array", "A variable", "A function"], answer: "Map with weak key references", explanation: "WeakMap holds weak references to keys, allowing garbage collection." },
  { level: 9, question: "What is Symbol?", options: ["Unique immutable identifier", "A character", "A variable", "A function"], answer: "Unique immutable identifier", explanation: "Symbol is a primitive type that creates a unique identifier." },
  { level: 9, question: "What is Proxy?", options: ["Intercepts object operations", "A function", "A variable", "A type"], answer: "Intercepts object operations", explanation: "Proxy allows intercepting and customizing operations on objects." },
  { level: 9, question: "What is the temporal dead zone?", options: ["Period before variable initialization", "A time period", "A zone in memory", "An error state"], answer: "Period before variable initialization", explanation: "TDZ is the period between entering scope and variable declaration being reached." },

  // Level 10: Expert Topics
  { level: 10, question: "What is the difference between call, apply, and bind?", options: ["call/apply invoke immediately, bind returns function", "No difference", "They're the same", "call is faster"], answer: "call/apply invoke immediately, bind returns function", explanation: "call() and apply() invoke immediately, bind() returns a function." },
  { level: 10, question: "What is context binding?", options: ["Setting the 'this' value", "Creating bindings", "Connecting functions", "Defining variables"], answer: "Setting the 'this' value", explanation: "Context binding determines what 'this' refers to in a function." },
  { level: 10, question: "What is a generator function?", options: ["Function that can be paused and resumed", "Generates data", "Creates functions", "Defines variables"], answer: "Function that can be paused and resumed", explanation: "Generator functions use yield to pause and resume execution." },
  { level: 10, question: "What is iterators and iterables?", options: ["Objects with iteration behavior", "Loops", "Arrays", "Functions"], answer: "Objects with iteration behavior", explanation: "Iterables provide iteration protocol, iterators control iteration." },
  { level: 10, question: "What is reflect API?", options: ["Built-in object for interceptable operations", "A mirror", "A function", "A variable"], answer: "Built-in object for interceptable operations", explanation: "Reflect API provides methods for interceptable JavaScript operations." },
  { level: 10, question: "What is the difference between var, let, and const?", options: ["var is function-scoped, let/const are block-scoped", "No difference", "They're the same", "var is faster"], answer: "var is function-scoped, let/const are block-scoped", explanation: "var has function scope, let/const have block scope, const cannot be reassigned." },
  { level: 10, question: "What is JavaScript engine?", options: ["Software that interprets JavaScript code", "A tool", "A library", "A framework"], answer: "Software that interprets JavaScript code", explanation: "JavaScript engine interprets and executes JavaScript code." },
  { level: 10, question: "What is JIT compilation?", options: ["Just-In-Time compilation for better performance", "A type of function", "An error", "A variable"], answer: "Just-In-Time compilation for better performance", explanation: "JIT compilation compiles code to machine code during execution for better performance." },
  { level: 10, question: "What is memory leak?", options: ["Unused memory not released", "A type of error", "A security issue", "A performance feature"], answer: "Unused memory not released", explanation: "Memory leak occurs when memory is allocated but never freed." },
  { level: 10, question: "What is garbage collection?", options: ["Automatic memory management and deallocation", "Cleaning code", "Removing files", "Deleting variables"], answer: "Automatic memory management and deallocation", explanation: "Garbage collection automatically frees memory that's no longer in use." },
];
